# Generated by Django 3.2 on 2021-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
