# Generated by Django 3.2 on 2021-04-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
    ]
